export const FECTCH_PRODUCTS_REQUEST = "FECTCH_PRODUCTS_REQUEST";
export const FECTCH_PRODUCTS_SUCCESS = "FECTCH_PRODUCTS_SUCCESS";
export const FECTCH_PRODUCTS_FAILURE = "FECTCH_PRODUCTS_FAILURE";

export const FILTER_PRODUCTS_BY_SIZE = "FILTER_PRODUCTS_BY_SIZE";
export const ORDER_PRODUCTS_BY_PRICE = "ORDER_PRODUCTS_BY_PRICE";
