export const FECTCH_PRODUCTS_REQUEST = "FECTCH_PRODUCTS_REQUEST";
export const FECTCH_PRODUCTS_SUCCESS = "FECTCH_PRODUCTS_SUCCESS";
export const FECTCH_PRODUCTS_FAILURE = "FECTCH_PRODUCTS_FAILURE";

export const FILTER_PRODUCTS_REQUEST = "FILTER_PRODUCTS_REQUEST";
export const ORDER_PRODUCTS_REQUEST = "ORDER_PRODUCTS_REQUEST";
export const SEARCH_PRODUCTS_REQUEST = "SEARCH_PRODUCTS_REQUEST";
